import {HomePage, LoginPage} from "../pages/home_page"

describe('Testcase B2C without login', function(){
    let homePage = new HomePage()
        it('Test to verify HomePage Header', function(){
            homePage.naviagteURL('https://dunzo-proxy-webpod.dunzodev.in/order')
            cy.get('[href="/partner"] > .sc-2b7yhw-0').should('have.text','Dunzo for Partners')
            cy.get('[href="/business"] > .sc-2b7yhw-0').should('have.text','Need Delivery Partners?')
            cy.get('.sc-64ptou-0.haEKYf').should('be.visible')
            cy.get('.GmqgG > .sc-1gu8y64-0').should('have.text','Sign in')
        })
        it('Test to verify serviceable cities', function(){
            cy.scrollTo('bottom')
            cy.get(':nth-child(3) > .sc-1felxgn-5').should('have.text','Serviceable Cities')
            cy.get(':nth-child(3) > .sc-1woi3cc-0 > :nth-child(1) > .jxbqi7-0').should('have.text','Bangalore').click().url().should('include','/bangalore')
            cy.scrollTo('bottom')
            cy.get(':nth-child(3) > .sc-1woi3cc-0 > :nth-child(2) > .jxbqi7-0').should('have.text','Pune').click().url().should('include','/pune')
            cy.scrollTo('bottom')
            cy.get(':nth-child(3) > .sc-1woi3cc-0 > :nth-child(3) > .jxbqi7-0').should('have.text','Gurgaon').click().url().should('include','/gurgaon')
            cy.scrollTo('bottom')
            cy.get(':nth-child(3) > .sc-1woi3cc-0 > :nth-child(4) > .jxbqi7-0').should('have.text','Hyderabad').click().url().should('include','/hyderabad')
            cy.scrollTo('bottom')
            cy.get(':nth-child(3) > .sc-1woi3cc-0 > :nth-child(5) > .jxbqi7-0').should('have.text','New Delhi').click().url().should('include','/delhi')
            cy.scrollTo('bottom')
            cy.get(':nth-child(3) > .sc-1woi3cc-0 > :nth-child(6) > .jxbqi7-0').should('have.text','Chennai').click().url().should('include','/chennai')
            cy.scrollTo('bottom')
            cy.get(':nth-child(3) > .sc-1woi3cc-0 > :nth-child(7) > .jxbqi7-0').should('have.text','Mumbai').click().url().should('include','/mumbai')
        })
        it('Test to verify Homescreen widegts', function(){
            cy.get('.dWkYtl > .sc-10mkyz7-0 > .sc-1gu8y64-0').click()
            cy.get('#places-autocomplete').type('Indiranagar')
            cy.get('.sc-1jxethi-0 > :nth-child(2)').click()
            cy.get('.sc-861fib-1 > .sblcwm-0 > .r1sxxf-0 > .sc-10mkyz7-0 > .sc-1gu8y64-0').should('have.text','Instant Delivery at your Doorstep')
            cy.get('[href="/order/grocery-stores"] > .sc-1go0t46-0').should('be.visible')
            cy.get('[href="/order/send-packages"] > .sc-1go0t46-0').should('be.visible')
            cy.get('[href="/order/bike-ride"] > .sc-1go0t46-0').should('be.visible')
            cy.get('[href="/order/restaurants"] > .sc-1go0t46-0').should('be.visible')
            cy.get('[href="/order/pet-supply-stores"] > .BbwkM').should('be.visible')
            cy.get('[href="/order/meat-and-fish-stores"] > .sc-1gu8y64-0').should('be.visible')
            cy.get('[href="/order/health-and-wellness-stores"] > .sc-1gu8y64-0').should('be.visible')
            cy.get('[href="/order/gifts"] > .BbwkM').should('be.visible')
            cy.get('[href="/order/medical-stores"] > .sc-1gu8y64-0').should('be.visible')
            cy.get('[href="/order/paan"] > .sc-1gu8y64-0').should('be.visible')            
        })
        it('Test to verify areas we deliver to', function(){
            cy.scrollTo(0, 500)  
            cy.get('.sc-1rutx3f-1 > .sc-1gu8y64-0').should('have.text','Areas we deliver to')      
        })

})